# Generated by Django 3.1.2 on 2020-11-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201109_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='thumbnail',
        ),
    ]
